### ISSUE TITLE
Consider renaming the project to tsc-bundle

### ISSUE THREAD

**Issue by RicoSuter** [sinclairzx81/typescript-bundle#2]
... to be consistent with the npm module name

**Comment by sinclairzx81** [comment]
The naming of the project / cli was in an attempt to align with the typescript compiler and its cli naming.
### typescript
```
npm install typescript -g
tsc ./app.ts
```
### typescript-bundle
```
npm install typescript-bundle -g
tsc-bundle ./app.ts ./app.js
```

I don't have too many strong feelings about it, but retaining "typescript" in the project name does help search engines and people locate the project. And project discovery is fairly important.

For now, I think I'm keen to retain the project name. But I will leave this issue here, perhaps remind me in a few months time and let's discuss. 

Many Thanks!
sinclair

**Comment by sinclairzx81** [comment]
Hi, thanks for your inputs on this. I am pretty happy with the naming as it is for now, but happy to reopen this issue at a later time. 

Many Thanks
